build:
  python_version: "3.8"  # Ensure this matches your development environment
  python_packages:
    - torch==1.9.0  # Adjust the version as per your model's requirements
    - diffusers==0.10.2  # For diffusion-based models
    - transformers==4.11.3  # For handling transformer architectures
    - cog==0.1.1  # Cog CLI for model deployment
  system_packages:
    - git  # Required for cloning repositories
    - libgl1-mesa-glx  # Necessary for OpenCV if used in your project

predict: "predict.py:Predictor"  # Ensure this points to your prediction class
